name: Experimentando con contextos
on: 
  workflow_dispatch:
    inputs:
      dia:
        description: 'Queremos saber que día de la semana es hoy'
        type: choice
        required: true
        default: Lunes
        options:
          - Lunes
          - Martes
          - Miercoles
          - Jueves
          - Viernes
          - Sabado
          - Domingo
      ganas_de_trabajar:
        description: 'Preguntamos al usuario como de motivado se siente para trabajar hoy'
        required: true
        default: false
        type: bool
env:
  Empresa: Atmira
jobs:
  Entresemanayconganasdetrabajar:
    if: ${{ inputs.ganas_de_trabajar == true && inputs.dia != 'Sabado' || inputs.dia != 'Domingo'  }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Greet the user
        run: echo Que bueno tener por aqui este ${{ inputs.dia }} entre semana en ${{ env.Empresa}}. Aunque no esperaba menos de ti, que vengas con ganas de trabajar es bueno.
  Entresemanaysinganasdetrabajar:
    if: ${{ inputs.ganas_de_trabajar == false && inputs.dia != 'Sabado' || inputs.dia != 'Domingo'  }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Greet the lazy user
        run: echo Hola, hoy es ${{ inputs.dia }} en ${{ env.Empresa}}. ¿Cual es el motivo por el que no vienes contento hoy a trabajar? ¿Como te puedo ayudar a mejorar tu rendimiento? 
 
  Findesemanayconganasdetrabajar:
    if: ${{ inputs.ganas_de_trabajar == true && inputs.dia == 'Sabado' || inputs.dia == 'Domingo'  }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Greet the user with joy
        run: echo Hey Hey Hey, hoy es ${{ inputs.dia }} y es fin de semana. Es estupendo que vengas a trabajar hoy motivado, en ${{ env.Empresa}} valoramos mucho tu actitúd.
  Findesemanaysinganasdetrabajar:
    if: ${{ inputs.ganas_de_trabajar == false && inputs.dia == 'Sabado' || inputs.dia == 'Domingo'  }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Greet the user
        run: echo Feliz dia de ${{ inputs.dia }} y fin de semana. No hace falta que trabajes hoy si esta cansado, tomate el dia libre!
